// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "AVANTPART", "          Nut Opener Email  info@avantpart.com  AVANTPART  Best Sellers  Nut Opener    Latest Arrivals T-Shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit Integer nec odio Praesent libero Sed cursus ante dapibus diam Sed nisi Nulla quis sem at nibh elementum imperdiet Duis sagittis ipsum Praesent mauris Fusce nec tellus sed augue semper porta   Best in 2025    Avantpart  Pioneering Innovation in Modern Solutions – Your Gateway to Cutting-Edge Technology, Creative Design, and Seamless Experiences Explore a World of Possibilities with Our Expertly Crafted Tools, Services, and Insights Join Us on a Journey to Transform Ideas into Reality, Where Innovation Meets Excellence Discover the Future Today with Avantpart – Redefining Boundaries, Inspiring Progress, and Empowering Success in Every Step Let’s Build Tomorrow, Together  Nut Opener  Mini Split Air Conditioner 12000 BTU With-30°C Heating Pump   ", "");
   this[database_length++] = new SearchPage("12000btu-air-conditioner.html", " 12000 BTU Inverter AC Heating to (Heating Pump) -30°C ", "NEW INSPIRATION 2025     NEW INSPIRATION 2025    Mini Split Air Conditioner 12000 BTU With-30°C Heating Pump  Email  info@avantpart.com  AVANTPART  The Ultimate Choice for Heating and Cooling in Any Condition!     Heating Even at -22°F  -30°C !  With advanced intelligent preheating technology and electric heating system, this unit provides comfortable warmth even on the coldest winter days    Inverter Cooling and Heating  Equipped with a GMCC compressor using R410A refrigerant, this unit operates quietly and efficiently Inverter technology ensures energy savings and extends the lifespan of the device  23,5 SEER2     Wi-Fi Remote Control  Control your air conditioner from anywhere using the mobile app  Android/iOS  and enjoy a comfortable environment at all times    FrostClean Technology  An advanced anti-frosting system that ensures optimal performance in any condition    Excellent Cooling and Heating Capacity  With a wide cooling and heating capacity range , this unit is suitable for various spaces    Quiet Design  With low noise levels , it brings peace and quiet to your home    Easy Installation with 5m Copper Pipe and Cable  The unit comes with a 5-meter copper pipe and cable, making installation quick and hassle-free    Wide Operating Temperature Range  This unit operates effectively in temperatures ranging from -22°F to 122°F  -30°C to 50°C     Trusted Bestcold Brand  With the reliability and after-sales service of the Bestcold brand, this unit is a dependable choice for your home or office 12000 BTU Inverter Air Conditioner  Heating and Cooling Down to -30°C   ", "12000 BTU mini split air conditioner & heat pump provides powerful cooling/heating. Energy-efficient, wall-mounted AC with Wi-Fi control.");
   this[database_length++] = new SearchPage("Nut-Cracker.html", "Untitled Page", "NEW INSPIRATION 2025     NEW INSPIRATION 2025    Nut Opener  Email  info@avantpart.com  AVANTPART  STAINLESS STEEL build made from heavy duty 304 stainless steel that resists rust, corrosion and tarnishing, guaranteeing long-lasting performance whether you're cracking walnuts daily or using occasionally for holiday preparations    NUT CRACKERS for all nuts for macadamias, walnuts and pecans, smart pressure system cracks tough shells perfectly while keeping kernels whole Stainless steel lever mechanism, macadamia nut cracker and nut crackers for pecans     NUTCRACKER SETS with picks professionally designed with a contoured grip and needle sharp point to carefully pry out intact walnut, pecan and macadamia kernels from their shells without leaving behind sharp fragments or damaging the meat      KITCHEN GADGETS this versatile nut cracker tool features a built in hanging hook for compact storage in kitchens, RVs, or campers, keeping your cooking area organized while remaining instantly accessible for cracking walnuts, pecans, and more      SEAFOOD TOOLS transitions seamlessly from cracking walnuts to shucking oysters, with a corrosion resistant stainless steel construction that withstands saltwater exposure while providing superior leverage for stubborn shells  ", "");
   return this;
}
